---

- name: install racktables dependancies
  yum: name={{ item }} state=latest
  with_items:
    - httpd
    - php-common
    - php-cli
    - php-ldap
    - php-snmp
    - php-pcntl
    - MySQL-python
  tags:
  - racktables

- name: install racktables
  yum: name=RackTables-{{ ver }} state=present
  tags:
  - racktables

- name: httpd racktables.conf
  template: src=racktables.conf.j2 dest=/etc/httpd/conf.d/racktables.conf owner=root group=root mode=0644
  notify:
  - restart httpd
  tags:
  - racktables

- name: enable httpd
  service: name=httpd enabled=true state=started
  tags:
  - racktables

- name: enable mysqld
  service: name=mysqld enabled=true state=started
  tags:
  - racktables

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags:
  - racktables

- name: setup db 
  mysql_db: name=racktables state=present
  tags:
  - racktables

- name: setup db user and pass
  mysql_user: name=racktablesuser password=rackpw priv=racktables.*:ALL state=present
  tags:
  - racktables

- name: check if secret.php exists - idempotent hack
  command: /bin/ls /etc/RackTables/secret.php
  ignore_errors: True
  register: result
  changed_when: False
  tags:
  - racktables

- name: prep secret.php
  file: path=/etc/RackTables/secret.php owner=root group=root mode=0666 state=touch
  when: result|failed
  tags:
  - racktables
