- include: init.yml

- name: Ensure ansible module dependancies are met
  yum: name={{ item }} state=present
  with_items:
      - python-setuptools
      - libselinux-python
  tags:
    - packages

- name: install pip
  easy_install: name=pip
  #  environment: proxy_env

- name: Add Elasticsearch repo key
  rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present
  #environment: proxy_env
  tags:
    - configuration

- name: Enable Elasticsearch repository
  template: src=etc/yum.repos.d/elasticsearch.repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644
  tags:
    - configuration

- name: Ensure elasticsearch and dependancies are installed
  yum: name={{ item }} state=present
  with_items:
    #    - java-1.7.0-openjdk
    - java-1.8.0-openjdk
    - elasticsearch
  tags:
    - packages

- name: Configure elasticsearch
  template: src=etc/elasticsearch/elasticsearch.conf.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=root group=root mode=0644
  notify:
    - restart elasticsearch
  tags:
    - configuration

- name: Allow elasticsearch to open more files
  template: src=etc/security/limits.d/50-elasticsearch.conf.j2 dest=/etc/security/limits.d/50-elasticsearch.conf owner=root group=root mode=0644
  notify:
    - restart elasticsearch
  tags:
    - configuration

- name: Modify elasticsearch service for ulimit -l unlimited to allow mlockall to work correctly
  template: src=etc/sysconfig/elasticsearch.j2 dest=/etc/sysconfig/elasticsearch owner=root group=root mode=0644
  notify:
    - restart elasticsearch
  tags:
    - configuration

- name: create required systemd service directory
  file: name=/etc/systemd/system/elasticsearch.service.d owner=root group=root mode=0755 state=directory
  tags:
    - configuration

- name: Modify systemd for mlockall to work correctly - new to systemd and elastic5 I think
  template: src=etc/systemd/system/elasticsearch.service.d/elasticsearch.conf.j2 dest=/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf owner=root group=root mode=0644
  #  notify:
    #  - reload systemd
  tags:
    - configuration

- name: Enable elasticsearch
  service: name=elasticsearch state=running enabled=true
  tags:
    - services

# install plugins
- include: plugins.yml
  when: es_install_plugins
  tags: [elasticsearch, elasticsearch-plugins]

- name: Install elasticsearch curator.
  pip: name=elasticsearch-curator
  #environment: proxy_env
  tags:
    - packages

- name: Setup elasticsearch_curator cron job
  template: src=etc/cron.daily/elasticsearch_curator.j2 dest=/etc/cron.daily/elasticsearch_curator owner=root group=root mode=0644
  notify:
    - restart cron
  tags:
    - configuration

- name: Configure logrotate for elasticsearch
  template: src=etc/logrotate.d/elasticsearch.j2 dest=/etc/logrotate.d/elasticsearch owner=root group=root mode=0644
  tags:
    - configuration

- name: Configure logrotate for elasticsearch curator
  template: src=etc/logrotate.d/elasticsearch_curator.j2 dest=/etc/logrotate.d/elasticsearch_curator owner=root group=root mode=0644
  tags:
    - configuration

- name: Prevent swapping except for emergency memory situations
  sysctl: name=vm.swappiness value=1 state=present
  tags:
    - configuration

- name: Giving it the virtual memmory needed for mmapped files
  sysctl: name=vm.max_map_count value=262144 state=present
  tags:
    - configuration

- name: create tmp location mounted with exec
  file: name=/usr/share/elasticsearch/tmp owner=elasticsearch group=root mode=0754 state=directory
  tags:
    - configuration
